### ISSUE TITLE
[10분 테코톡] 스프링 프록시

### ISSUE THREAD

**Issue by gutenLEE** [WanOnPreStudy/WooTechVideoStudy#1]
1. [10분 테코톡] 기론, 리버의 JDK Dynamic Proxy와 CGLIB  
[영상 링크](https://www.youtube.com/watch?v=MFckVKrJLRQ&list=PLgXGHBqgT2TvpJ_p9L_yZKPifgdBOzdVH&index=29)

2. [10분 테코톡] 후니의 스프링 트랜잭션
[영상 링크](https://www.youtube.com/watch?v=cc4M-GS9DoY&t=2s)

선정 이유!
원티드 과제 중 트랜잭션의 연장선상,
그리고 스프링의 트랜잭션 동작 원리를 이해하기 위해서는 프록시도 알아야 하므로 이 주제를 선택했습니다.
+ 2개의 영상중에 하나 선택하시면 됩니다!

**Comment by Hijiji** [comment]
하나의 비즈니스 로직에서 두번의 업데이트 쿼리 생성 - 각 업데이트 쿼리는 새로운 트랜젝션을 생성하여데이터베이스에 저장한다. 이 때 각 쿼리마다 트랜잭션을 커밋하기 때문에 런타임 익셉션이 발생되면 하나의 쿼리문만 실행된 후에 종료된다. 
그렇기 때문에 하나의 비즈니스 로직을 단일트랜잭션으로 관리해야한다.

하나의 비즈니스 로직을 단일트랜잭션으로 관리하는 방법

순수 JDBC
트랜젝션을 비지니스 로직 시작하기 전에 열어주고 종료되면 닫아주는 로직으로 트랜젝션의 경계를 설정해준다.
문제점 : Service코드가 복잡해지고 데이터액세스 기술에 의존적인 코드를 작성하게되며 비즈니스 로직과는 다른 관심사의 일을 수행하게된다.
Connection conn = getConnettion()
conn.setAutoCommit(false);
비즈니스로직();
conn.commit(); or conn.rollback();
conn..setAutoCommit(true);
conn.close();


JPA사용

Spring에서 제공하는 트랜잭션관리
1. 트랜잭션 동기화
- 데이터접근 기술과 트랜잭션 사이의 종속성 제거
how? SpringBoot에서 제공하는 DataSourceUtils를 이용해 Connection을 생성한다. 
커넥션은 TransactionSynchronizationManager에 저장한다.
트랜젝션 동기화 매니저에 저장된 커넥션이 존재하면 JDBC템플릿이 쿼리를 날릴 때 트랜잭션 동기화 매니저에 저장된 커넥션을 가져온다.
이로 인해 두 업데이트 쿼리가 하나의 로컬 트랜잭션으로 관리된다.
2. 트랜잭션 추상화
- 트랜잭션을 쉽게 활용
Spring은 PlatformTransactionManager Interface를 만들어서 각 구현체들이 트랜잭션을 가져오는 방식을 명세로 추상화해두었다. 그러면 데이터접근기술에 관계없이 트랜잭션 동기화 매니저에 트랜잭션을 가져오게된다. 
결국 특정데이터기술에 의존하지 않게 되는것이다.
3. 선언적 트랜잭션
- 비지니스 로직과 트랜잭션 로직을 분리한다.
스프링은 선언적 트랜잭션을 사용해서 트랜잭션을 생성하고 종료하는 일을 비즈니스 로직과 분리하게 도와준다.
how? @Transactional 어노테이션 !
AOP(Aspect Oriented Programming)으로 구현된 트랜잭셔널 어노테이션을 통해서타겟 매서드를 가진 클래스를 상속받아서 트랜잭션 경계로 감싼 프록시(proxy)를 만든다.
그러면 트랜잭션 경계설정을 하는 다른 관심사의 코드를 완벽하게 분리할 수 있게된다. 순수 비지니스로직만 남게된다

사용방법?
이 선언적트랜잭션은 타겟객체의 메서드부터 탐색한다.
1. 클래스에 어노테이션을 달아서 공통적으로 옵션을 사용할 수 있고
2. 메서드별로 어노테이션을 달아서 세부적으로 옵션을 지정해줄 수 있다.



트랜잭션의 속성

전파 propatation - 트랜잭션을 시작하거나 참여하는 방법을 정하는 속성
     Required : 트랜잭션이 있으면 참여하고 없으면 새로시작함. 디폴트
     Requires_New : 항상새로운 트랜잭션을 시장함. 진핸중인 트랜잭션이 있으면 잠시보류함
     Suppors : 기존의 트랜잭션에 참여함. 없으면 트랜잭션 없이 진행.
     Nested : 이미진행중인 트랜잭션에 중첩 트랜잭션을 시작함. 부모트랜잭션 커밋, 롤백에 영향 받음. 부모에게 영향을 줄 수 없음
     Never : 트랜잭션사용안함. 트랜잭션존재하면 예외발생
     Not_supported : 트랜잭션사용안함. 트랜잭션이 있으면 보류

고립 isolation -트랜잭션 격리수준을 나타내는 속성. 여러 트랜잭션이 진행될 떄 트랜잭션의 작업결과를 타 트랜잭션에게 어떻게 노출할지 결정함
     Default : 사용하는데이터접근 기술이나 DB드라이버의 기본설정을 따름. Oracle은 Read_Commited, Mysql은 Repeatable_read를 기본격리수준으로 가짐
     Read_uncommited : 가장 낮은 격리수준 트랜잭션. 커밋하지 않은 데이터의 정보도 읽음. 정확성은 떨어지지만 성능이 좋아서 극대화할 때 사용.
     Read_Commited : 커밋하지 않은 정보는 읽을 수 없음. 읽는 시점에 따라 데이터가 변경될 수 있음
     Repeatable_read : 다른 트랜잭션이 읽는 정보를 수정, 반영할 수 없음. 커밋되면 스냅샷을 찍어서 스냅샷의 정보를 읽기 떄문
     Serializable : 격리성이 굉장히 높음. 극단적으로 안전한 작업이 필요한 경우에만 가끔사용

읽기동작 read-only - 힌트로 사용되고 트랜잭션 내에서 데이터를 조작하려는 시도를 막음. 단 데이터접근기술, 사용DB에 따라 적용차이가 있음.(힌트를 구현하지 않으면 쓰기행동이 발생되어도 예외발생안됨)

타임아웃 time-out - 트랜잭션에 제한시간 지정하는 옵션. 기본옵션에는 제한시간이 없지만 별도로 지정가능. Required나 Requires_New와 같이 새로운 트랜잭션을 시작하는 전파옵션과 함꼐 사용할 수 있도록 고안한 옵션.

rollback-for (선언적트랜잭션만가능) - CheckedException 을ㅡ 롤백대상으로 삼고싶을 때 해당옵션 추가하면 사용가능

no-rollback-for (선언적트랜잭션만가능) - RuntimeException이 발생해도 커밋대상으로 삼고싶을 때 해당옵션 사용
